model:
  module: 'Model'
  class: 'CNN1DAE'
  args:
    input_dim: 21
    hidden_dim: 64
    kernel_size: 3
    stride: 2
    padding: 1
    output_padding: 1

training:
  epochs: 50
  learning_rate: 0.001
  optimizer:
    type: 'Adam'
    args:
      weight_decay: 0.0001

testing:
  threshold: 0.035

loss:
  type: 'MSELoss'
  args: {}

dataset:
  module: 'Module.anomalydata'
  class: 'AnomalDataset'
  preprocessing_arg: 'processing'
  args:
    preprocessing:
      module: 'Module.preprocessing'
      function: 'processing'
      args:

    train:
      args:
        root_dir: './data/robot_action'
        seq_length: 250
        mode: train
      loader:
        batch_size: 64
        shuffle: True
    test:
      args:
        root_dir: './data/robot_action'
        seq_length: 250
        mode: test
      loader:
        batch_size: 100
        shuffle: True

visualization:
  enabled: True
  plot_dir: './plots'

export_results:
  enabled: True
  export_dir: './results'
