model:
  module: 'Model'
  class: 'TransformerClassifier'
  args:
    input_dim: 21
    num_classes: 6
    d_model: 64
    nhead: 4
    num_layers: 2
    dim_feedforward: 128
    dropout: 0.1

training:
  epochs: 50
  learning_rate: 0.001
  optimizer:
    type: 'Adam'
    args:
      weight_decay: 0.0001

testing:
  metric: ['accuracy']

loss:
  type: 'CrossEntropyLoss'
  args: {}

dataset:
  module: 'Module.dataset'
  class: 'ActionDataset'
  preprocessing_arg: 'processing'
  args:
    preprocessing:
      module: 'Module.preprocessing'
      function: 'processing'
      args:

    train:
      args:
        root_dir: './data/robot_action'
        seq_length: 250
        mode: 'train'
      loader:
        batch_size: 64
        shuffle: True
    valid:
      args: 
        root_dir: './data/robot_action'
        seq_length: 250
        mode: 'valid'
      loader: 
        batch_size: 64
        shuffle: True
    test:
      args:
        root_dir: './data/robot_action'
        seq_length: 250
        mode: 'test'
      loader:
        batch_size: 100
        shuffle: False

visualization:
  enabled: True
  plot_dir: './plots'

export_results:
  enabled: True
  export_dir: './Results'
